package com.jlisok.youtube_activity_manager.domain.exceptions;

public enum ResponseCode {

    REGISTRATION_FAILED_UNEXPECTED_ERROR,
    REGISTRATION_FAILED_VIOLATED_FIELD_EMAIL,
    REGISTRATION_FAILED_PREFIX_PHONE_NUMBER_MUST_BE_FILLED_IN_OR_NULL,
    REGISTRATION_FAILED_SOME_PARAMETERS_NULL,

    LOGIN_FAILED_PARAMETERS_DO_NOT_MATCH_DATABASE,
    LOGIN_FAILED_GOOGLE_TOKEN_INVALID,
    LOGIN_FAILED_EMAIL_NOT_VERIFIED,
    LOGIN_FAILED_GOOGLE_ACCOUNT_ALREADY_EXISTS

}
